Apm 1276 asid required
NHSDigital/personal-demographics-service-api pull request #356
Opened 2020-09-04 13:16 UTC by Sourceless

* Add in some templating and config for requiring (or not requiring) an ASID

2020-09-08 13:30 UTC, Sourceless commented
/azp run

2020-09-08 13:46 UTC, Sourceless commented
/azp run

2020-09-10 14:13 UTC, Sourceless commented
/azp run

2020-09-11 14:18 UTC, strutt requested changes

2020-09-11 14:18 UTC, strutt commented on proxies/live/apiproxy/targets/ig3.xml
> +            {% endif %}
Swap the order of these steps

2020-09-14 10:02 UTC, Sourceless commented on proxies/live/apiproxy/targets/ig3.xml
> +                <Condition>(request.header.NHSD-ASID is null) or (not request.header.NHSD-ASID ~~ ".+")</Condition>
This condition needs changing the variable assigned by the next step

2020-09-14 13:55 UTC, Sourceless commented
/azp run

2020-09-14 14:27 UTC, Sourceless commented
/azp run

2020-09-15 07:49 UTC, Sourceless commented
/azp run

2020-09-15 09:47 UTC, strutt approved these changes

2020-09-15 09:47 UTC, merged