Added new /FHIR/R4 base path [Don't merge]
NHSDigital/personal-demographics-service-api pull request #540
Opened 2021-01-28 14:55 UTC by TomSmithCoding

## Summary
* Routine Change
* :exclamation: Breaking Change
* :robot: Operational or Infrastructure Change
* :sparkles: New Feature
* :warning: Potential issues that might be caused by this change

Add any other relevant notes or explanations here. **Remove this line if you have nothing to add.**

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [ ] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

2021-02-01 09:42 UTC, TomSmithCoding commented
/azp run

2021-02-08 15:45 UTC, TomSmithCoding commented
/azp run

2021-02-08 16:07 UTC, TomSmithCoding commented
/azp run

2021-02-08 16:33 UTC, TomSmithCoding commented
/azp run

2021-02-08 16:56 UTC, TomSmithCoding commented
/azp run

2021-02-09 12:26 UTC, TomSmithCoding commented
/azp run

2021-02-09 14:22 UTC, TomSmithCoding commented
/azp run

2021-02-10 14:23 UTC, TomSmithCoding commented
/azp run

2021-02-10 14:35 UTC, TomSmithCoding commented
/azp run

2021-02-12 16:17 UTC, TomSmithCoding commented
/azp run

2021-02-16 15:19 UTC, TomSmithCoding commented
/azp run

2021-02-16 16:32 UTC, TomSmithCoding commented
/azp run

2021-02-19 11:40 UTC, TomSmithCoding commented
/azp run

2021-02-21 23:43 UTC, TomSmithCoding commented
/azp run

2021-02-23 16:49 UTC, alexhawdon requested changes

2021-02-23 16:49 UTC, alexhawdon commented on proxies/live/apiproxy/resources/jsc/URLRewrite.js
> +  print("proxy.pathsuffix is: " + path)
remove

2021-02-23 16:49 UTC, alexhawdon commented on proxies/sandbox/apiproxy/resources/jsc/URLRewrite.js
> +  print("proxy.pathsuffix is: " + path)
Remove

2021-02-23 16:49 UTC, alexhawdon commented on proxies/sandbox/apiproxy/resources/jsc/URLRewrite.js
> +  //queryParams = context.getVariable('request.querystring')
Remove

2021-02-23 16:49 UTC, alexhawdon commented on tests/user_restricted/test_user_restricted.py
> +        # Light weighted tests to ensure we cah hit the old end points
Convert to docstring

2021-02-23 17:18 UTC, alexhawdon requested changes

2021-02-23 17:18 UTC, alexhawdon commented on tests/user_restricted/test_user_restricted.py
> +        """Light weighted tests to ensure we cah hit the old end points"""
No not here - should be directly under the Class/Function definition

2021-02-23 17:22 UTC, alexhawdon approved these changes

2021-02-24 11:35 UTC, arvinkumarthoom approved these changes
Reviewed

2021-02-24 11:41 UTC, merged